[theme]
primaryColor = "#6c63ff"  # Cor principal (botões, links)
backgroundColor = "#f4f4f4"  # Cor de fundo
secondaryBackgroundColor = "#ffffff"  # Fundo do chat
textColor = "#333333"  # Cor do texto
font = "sans serif"
